<?php


function Users_Page_init()
{
	//drupal_set_message("hello worldddddddddd");
}
//hook_menu
function Users_Page_menu() {
	$items = array();
  $items['Users_Page_page'] = array(
    'title' => 'My Users Page',
    'description' => 'List of Users.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('UsersPage_showUsersPageForm'),
	'access callback'=>'user_access',
	'access arguments'=>array('access content'),
	'type'=>MENU_NORMAL_ITEM
    
   );
   
   
  return $items;
}
function UsersPage_showUsersPageForm()
{
	$form=array();
	// $query = db_query("Select * FROM {Users}");
	
	// $header= array(t('User'),t('Host'));
	// $rows = array();
	
	// foreach($results AS $result)
	// {
		// $rows[]=array(
		// $result->User,
		// $result ->Host,
		// );
	// }
	// return theme('table',array('header'=>$header,'rows'=>$rows));

	$form=array();
	$form['searchfield']=array(
	'#type'=>'textfield',
	'#title'=>'Search Input'
	
	);
	
	$form['button']=array(
	'#type'=>'button',
	'#value'=>'Search',
	'#weight' => 20,
	);
	return $form;
}